name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'tinyurl21'
          heroku_email: 'sanket.sonawane123@gmail.com'
        env:
          HD_FIREBASE_CREDS_BASE64: ${{secrets.FIREBASE_API_KEY}}
